apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: atomic-storage
  namespace: atomic
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: local
