apiVersion: apps/v1
kind: Deployment
metadata:
  name: filebrowser
  namespace: filebrowser
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filebrowser
  template:
    metadata:
      labels:
        app: filebrowser
    spec:
      containers:
        - name: filebrowser
          image: filebrowser/filebrowser:latest
          ports:
            - containerPort: 80
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          volumeMounts:
            - name: data
              mountPath: /srv
            - name: db
              mountPath: /database
      volumes:
        - name: data
          hostPath:
            path: /data/filebrowser
            type: DirectoryOrCreate
        - name: db
          hostPath:
            path: /data/filebrowserdb
            type: DirectoryOrCreate
