apiVersion: apps/v1
kind: Deployment
metadata:
  name: filebrowser
  namespace: filebrowser
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filebrowser
  template:
    metadata:
      labels:
        app: filebrowser
    spec:
      containers:
        - name: filebrowser
          image: filebrowser/filebrowser:latest
          ports:
            - containerPort: 80
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: FB_USER
              valueFrom:
                secretKeyRef:
                  name: filebrowser-auth
                  key: admin-user
            - name: FB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: filebrowser-auth
                  key: admin-password
          volumeMounts:
            - name: data
              mountPath: /srv
      volumes:
        - name: data
          hostPath:
            path: /data
            type: Directory
