apiVersion: v1
kind: Service
metadata:
  name: filebrowser
  namespace: filebrowser
spec:
  type: NodePort
  selector:
    app: filebrowser
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31100
