apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: homarr
  name: homarr
spec:
  ports:
    - name: "7575"
      port: 7575
      nodePort: 32501
      targetPort: 7575
  selector:
    io.kompose.service: homarr
  type: NodePort
#status:
  #  loadBalancer: {}
