apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
  name: db-redis
  namespace: dbs
spec:
  ports:
    - port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    app: redis
    tier: cache
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-redis
  namespace: dbs
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: redis
      tier: cache
  serviceName: db-redis
  template:
    metadata:
      labels:
        app: redis
        tier: cache
    spec:
      containers:
        - image: redis:3.2-alpine
          imagePullPolicy: IfNotPresent
          name: db-redis
          ports:
            - containerPort: 6379
              protocol: TCP
          volumeMounts:
            - name: pvc-redis
              mountPath: /data/redis
      restartPolicy: Always
      volumes:
        - name: pvc-redis
          persistentVolumeClaim:
            claimName: pvc-redis
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
