apiVersion: v1
kind: Pod
metadata:
  name: kali-pod
  namespace:
spec:
  containers:
  - name: kali-to-go
    image: pgnomme/kali-to-go:v2
    command: [ "bash", "-c", "while true; do sleep 3600; done" ]
    tty: true
    stdin: true

